"""initial schema

Revision ID: 37c486f7eb66
Revises:
Create Date: 2026-08-05 15:52:07.035297

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "37c486f7eb66"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Categorias_Insumos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=150), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nombre"),
    )
    op.create_table(
        "Clientes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column("documento_identidad", sa.String(length=100), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("telefono", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("documento_identidad"),
    )
    op.create_table(
        "Proveedores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column("ubicacion", sa.String(length=255), nullable=True),
        sa.Column("url", sa.String(length=500), nullable=True),
        sa.Column("contacto", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Socios_Configuracion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=150), nullable=False),
        sa.Column("porcentaje_participacion", sa.Numeric(precision=15, scale=4), nullable=False),
        sa.CheckConstraint("porcentaje_participacion > 0", name="ck_socios_participacion_positiva"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nombre"),
    )
    op.create_table(
        "Tipos_Producto",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=150), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nombre"),
    )
    op.create_table(
        "Usuarios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=150), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("rol", sa.String(length=20), nullable=False),
        sa.CheckConstraint("rol IN ('admin', 'operador', 'consulta')", name="ck_usuarios_rol"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "Insumos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("categoria_id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column("unidad_medida", sa.String(length=50), nullable=False),
        sa.Column("stock_actual", sa.Numeric(precision=15, scale=4), nullable=False),
        sa.Column("stock_minimo", sa.Numeric(precision=15, scale=4), nullable=False),
        sa.Column("costo_promedio_actual", sa.Numeric(precision=15, scale=4), nullable=False),
        sa.ForeignKeyConstraint(["categoria_id"], ["Categorias_Insumos.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Movimientos_Financieros",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "fecha", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("tipo", sa.String(length=20), nullable=False),
        sa.Column("descripcion", sa.String(length=500), nullable=False),
        sa.Column("monto", sa.Numeric(precision=15, scale=4), nullable=False),
        sa.Column("socio_id", sa.Integer(), nullable=True),
        sa.CheckConstraint("tipo IN ('Gasto', 'Inversion', 'Retiro')", name="ck_movimientos_tipo"),
        sa.ForeignKeyConstraint(["socio_id"], ["Socios_Configuracion.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Productos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tipo_producto_id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column("requiere_fabricacion", sa.Boolean(), nullable=False),
        sa.Column("costos_operativos_fijos", sa.Numeric(precision=15, scale=4), nullable=False),
        sa.Column("precio_venta_sugerido", sa.Numeric(precision=15, scale=4), nullable=False),
        sa.ForeignKeyConstraint(["tipo_producto_id"], ["Tipos_Producto.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Ventas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "fecha", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("cliente_id", sa.Integer(), nullable=True),
        sa.Column("descuento_porcentaje", sa.Numeric(precision=15, scale=4), nullable=False),
        sa.Column("estado", sa.String(length=20), nullable=False),
        sa.Column("total_venta", sa.Numeric(precision=15, scale=4), nullable=False),
        sa.CheckConstraint("estado IN ('completada', 'anulada')", name="ck_ventas_estado"),
        sa.ForeignKeyConstraint(["cliente_id"], ["Clientes.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "BOM_Productos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("combo_id", sa.Integer(), nullable=False),
        sa.Column("producto_incluido_id", sa.Integer(), nullable=False),
        sa.Column("cantidad", sa.Numeric(precision=15, scale=4), nullable=False),
        sa.ForeignKeyConstraint(["combo_id"], ["Productos.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["producto_incluido_id"], ["Productos.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("combo_id", "producto_incluido_id", name="uq_bom_productos_combo"),
    )
    op.create_table(
        "Compras_Insumos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("insumo_id", sa.Integer(), nullable=False),
        sa.Column("proveedor_id", sa.Integer(), nullable=True),
        sa.Column(
            "fecha_compra",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("cantidad_comprada", sa.Numeric(precision=15, scale=4), nullable=False),
        sa.Column("precio_unitario_compra", sa.Numeric(precision=15, scale=4), nullable=False),
        sa.ForeignKeyConstraint(["insumo_id"], ["Insumos.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["proveedor_id"], ["Proveedores.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Detalle_Ventas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("venta_id", sa.Integer(), nullable=False),
        sa.Column("producto_id", sa.Integer(), nullable=False),
        sa.Column("cantidad", sa.Numeric(precision=15, scale=4), nullable=False),
        sa.Column("precio_unitario_aplicado", sa.Numeric(precision=15, scale=4), nullable=False),
        sa.Column("costo_unitario_aplicado", sa.Numeric(precision=15, scale=4), nullable=False),
        sa.ForeignKeyConstraint(["producto_id"], ["Productos.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["venta_id"], ["Ventas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Devoluciones",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("venta_id", sa.Integer(), nullable=False),
        sa.Column(
            "fecha", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("motivo", sa.Text(), nullable=True),
        sa.Column("monto_reembolsado", sa.Numeric(precision=15, scale=4), nullable=False),
        sa.ForeignKeyConstraint(["venta_id"], ["Ventas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Variantes_Producto",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("producto_id", sa.Integer(), nullable=False),
        sa.Column("nombre_variante", sa.String(length=150), nullable=False),
        sa.Column("precio_venta", sa.Numeric(precision=15, scale=4), nullable=True),
        sa.ForeignKeyConstraint(["producto_id"], ["Productos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("producto_id", "nombre_variante", name="uq_variantes_producto_nombre"),
    )
    op.create_table(
        "BOM_Insumos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("producto_id", sa.Integer(), nullable=False),
        sa.Column("insumo_id", sa.Integer(), nullable=False),
        sa.Column("variante_id", sa.Integer(), nullable=True),
        sa.Column("cantidad_requerida", sa.Numeric(precision=15, scale=4), nullable=False),
        sa.Column("porcentaje_desperdicio", sa.Numeric(precision=15, scale=4), nullable=False),
        sa.ForeignKeyConstraint(["insumo_id"], ["Insumos.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["producto_id"], ["Productos.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["variante_id"], ["Variantes_Producto.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("producto_id", "insumo_id", "variante_id", name="uq_bom_insumos_combo"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("BOM_Insumos")
    op.drop_table("Variantes_Producto")
    op.drop_table("Devoluciones")
    op.drop_table("Detalle_Ventas")
    op.drop_table("Compras_Insumos")
    op.drop_table("BOM_Productos")
    op.drop_table("Ventas")
    op.drop_table("Productos")
    op.drop_table("Movimientos_Financieros")
    op.drop_table("Insumos")
    op.drop_table("Usuarios")
    op.drop_table("Tipos_Producto")
    op.drop_table("Socios_Configuracion")
    op.drop_table("Proveedores")
    op.drop_table("Clientes")
    op.drop_table("Categorias_Insumos")
    # ### end Alembic commands ###
