"""ventas canal y variante

Revision ID: 22aaf221d477
Revises: edb47feafc05
Create Date: 2026-08-07 12:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "22aaf221d477"
down_revision: str | None = "edb47feafc05"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Detalle_Ventas", sa.Column("variante_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_detalle_ventas_variante",
        "Detalle_Ventas",
        "Variantes_Producto",
        ["variante_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "Ventas",
        sa.Column("canal_venta", sa.String(length=16), server_default="feria", nullable=False),
    )
    op.create_check_constraint(
        "ck_ventas_canal_venta",
        "Ventas",
        "canal_venta IN ('web', 'whatsapp', 'instagram', 'feria')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_ventas_canal_venta", "Ventas", type_="check")
    op.drop_column("Ventas", "canal_venta")
    op.drop_constraint("fk_detalle_ventas_variante", "Detalle_Ventas", type_="foreignkey")
    op.drop_column("Detalle_Ventas", "variante_id")
    # ### end Alembic commands ###
