"""devolucion items y extension finanzas

Revision ID: a4f3c9d2b8e14f6a9c5e5b7d1a1a8e3c
Revises: 22aaf221d477
Create Date: 2026-08-07 16:20:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4f3c9d2b8e14f6a9c5e5b7d1a1a8e3c'
down_revision: Union[str, None] = '22aaf221d477'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # -- Devoluciones.tipo + usuario_id
    op.add_column(
        'Devoluciones',
        sa.Column('tipo', sa.String(length=16), nullable=True),
    )
    op.execute('UPDATE "Devoluciones" SET tipo = \'total\' WHERE tipo IS NULL')
    op.alter_column(
        'Devoluciones',
        'tipo',
        existing_type=sa.String(length=16),
        server_default='parcial',
        nullable=False,
    )
    op.create_check_constraint(
        'ck_devoluciones_tipo',
        'Devoluciones',
        "tipo IN ('parcial', 'total')",
    )
    op.add_column(
        'Devoluciones',
        sa.Column('usuario_id', sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        'fk_devoluciones_usuario',
        'Devoluciones',
        'Usuarios',
        ['usuario_id'],
        ['id'],
        ondelete='SET NULL',
    )

    # -- Items_Devolucion
    op.create_table(
        'Items_Devolucion',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('devolucion_id', sa.Integer(), nullable=False),
        sa.Column('producto_id', sa.Integer(), nullable=False),
        sa.Column('variante_id', sa.Integer(), nullable=True),
        sa.Column('cantidad', sa.Numeric(15, 4), nullable=False),
        sa.Column('precio_unitario', sa.Numeric(15, 4), nullable=False),
        sa.Column('subtotal', sa.Numeric(15, 4), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['devolucion_id'], ['Devoluciones.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['producto_id'], ['Productos.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['variante_id'], ['Variantes_Producto.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )

    # -- Movimientos_Financieros: estado + liquidacion_id + partial unique index
    op.add_column(
        'Movimientos_Financieros',
        sa.Column('estado', sa.String(length=20), server_default='activo', nullable=False),
    )
    op.add_column(
        'Movimientos_Financieros',
        sa.Column('liquidacion_id', sa.String(length=12), nullable=True),
    )
    op.create_index(
        'uq_liquidacion',
        'Movimientos_Financieros',
        ['liquidacion_id'],
        unique=True,
        postgresql_where=sa.text('liquidacion_id IS NOT NULL'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_liquidacion', table_name='Movimientos_Financieros')
    op.drop_column('Movimientos_Financieros', 'liquidacion_id')
    op.drop_column('Movimientos_Financieros', 'estado')

    op.drop_table('Items_Devolucion')

    op.drop_constraint('fk_devoluciones_usuario', 'Devoluciones', type_='foreignkey')
    op.drop_column('Devoluciones', 'usuario_id')
    op.drop_constraint('ck_devoluciones_tipo', 'Devoluciones', type_='check')
    op.drop_column('Devoluciones', 'tipo')
    # ### end Alembic commands ###