"""add es_regalo to ventas

Revision ID: 27d5c5b6fd80
Revises: d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9
Create Date: 2026-08-12 13:32:30.776455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27d5c5b6fd80'
down_revision: Union[str, None] = 'd4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Ventas', sa.Column('es_regalo', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Ventas', 'es_regalo')
    # ### end Alembic commands ###
