"""Add document states and reversal tracking fields

Revision ID: 98bda77bcd4d
Revises: 0008_remove_proveedores
Create Date: 2026-08-20 20:21:23.795230

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "98bda77bcd4d"
down_revision: str | None = "0008_remove_proveedores"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "AuditLog",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=True),
        sa.Column("usuario_rol", sa.String(length=20), nullable=False),
        sa.Column("entidad", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("accion", sa.String(length=20), nullable=False),
        sa.Column("valores_old", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("valores_new", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("ip", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column(
            "timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["usuario_id"], ["Usuarios.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_AuditLog_accion"), "AuditLog", ["accion"], unique=False)
    op.create_index(op.f("ix_AuditLog_entidad"), "AuditLog", ["entidad"], unique=False)
    op.create_index(op.f("ix_AuditLog_entity_id"), "AuditLog", ["entity_id"], unique=False)
    op.create_index(op.f("ix_AuditLog_request_id"), "AuditLog", ["request_id"], unique=False)
    op.create_index(op.f("ix_AuditLog_timestamp"), "AuditLog", ["timestamp"], unique=False)
    op.create_index(op.f("ix_AuditLog_usuario_id"), "AuditLog", ["usuario_id"], unique=False)
    op.create_index(
        "ix_auditlog_entidad_accion_fecha",
        "AuditLog",
        ["entidad", "accion", "timestamp"],
        unique=False,
    )
    op.create_index(
        "ix_auditlog_entidad_entity_id", "AuditLog", ["entidad", "entity_id"], unique=False
    )
    op.create_index("ix_auditlog_request_id", "AuditLog", ["request_id"], unique=False)
    op.create_index(
        "ix_auditlog_usuario_fecha", "AuditLog", ["usuario_id", "timestamp"], unique=False
    )

    # Add estado to Devoluciones with default for existing rows
    op.add_column(
        "Devoluciones",
        sa.Column("estado", sa.String(length=20), nullable=True, server_default="confirmed"),
    )
    op.add_column("Devoluciones", sa.Column("reversed_motivo", sa.Text(), nullable=True))
    op.add_column("Devoluciones", sa.Column("reversed_by", sa.Integer(), nullable=True))
    op.add_column(
        "Devoluciones", sa.Column("reversed_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(op.f("ix_Devoluciones_estado"), "Devoluciones", ["estado"], unique=False)
    op.create_foreign_key(
        None, "Devoluciones", "Usuarios", ["reversed_by"], ["id"], ondelete="SET NULL"
    )
    op.create_check_constraint(
        "ck_devoluciones_estado",
        "Devoluciones",
        "estado IN ('draft', 'confirmed', 'cancelled', 'reversed')",
    )

    # Now make estado non-nullable (server_default handles new rows, existing rows have 'confirmed')
    op.alter_column("Devoluciones", "estado", nullable=False, server_default="confirmed")

    op.add_column("Movimientos_Financieros", sa.Column("reversed_motivo", sa.Text(), nullable=True))
    op.add_column("Movimientos_Financieros", sa.Column("reversed_by", sa.Integer(), nullable=True))
    op.add_column(
        "Movimientos_Financieros",
        sa.Column("reversed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_foreign_key(
        None, "Movimientos_Financieros", "Usuarios", ["reversed_by"], ["id"], ondelete="SET NULL"
    )
    # Migrate the legacy `estado` domain (0004 set server_default='activo') to the
    # new document-state domain BEFORE the CHECK constraint is applied, so the
    # constraint never sees out-of-domain rows.
    op.execute(
        "UPDATE \"Movimientos_Financieros\" SET estado = 'confirmed' WHERE estado = 'activo'"
    )
    op.execute(
        "ALTER TABLE \"Movimientos_Financieros\" ALTER COLUMN estado SET DEFAULT 'confirmed'"
    )
    op.create_check_constraint(
        "ck_movimientos_estado",
        "Movimientos_Financieros",
        "estado IN ('draft', 'confirmed', 'cancelled', 'reversed')",
    )

    op.add_column("Ventas", sa.Column("reversed_motivo", sa.Text(), nullable=True))
    op.add_column("Ventas", sa.Column("reversed_by", sa.Integer(), nullable=True))
    op.add_column("Ventas", sa.Column("reversed_at", sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, "Ventas", "Usuarios", ["reversed_by"], ["id"], ondelete="SET NULL")
    # Migrate Ventas.estado from the legacy domain ('completada'/'anulada', from
    # 0001) to the new document-state domain before swapping the CHECK. Otherwise
    # a freshly-built schema rejects any Venta inserted with the model default
    # 'confirmed' (legacy ck_ventas_estado allowed only 'completada'/'anulada').
    op.execute("UPDATE \"Ventas\" SET estado = 'confirmed' WHERE estado = 'completada'")
    op.execute("UPDATE \"Ventas\" SET estado = 'cancelled' WHERE estado = 'anulada'")
    op.execute("ALTER TABLE \"Ventas\" ALTER COLUMN estado SET DEFAULT 'confirmed'")
    op.drop_constraint("ck_ventas_estado", "Ventas", type_="check")
    op.create_check_constraint(
        "ck_ventas_estado", "Ventas", "estado IN ('draft', 'confirmed', 'cancelled', 'reversed')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Restore the legacy Ventas domain and default before dropping the new CHECK.
    op.drop_constraint("ck_ventas_estado", "Ventas", type_="check")
    op.execute("UPDATE \"Ventas\" SET estado = 'completada' WHERE estado = 'confirmed'")
    op.execute(
        "UPDATE \"Ventas\" SET estado = 'anulada' "
        "WHERE estado IN ('cancelled', 'reversed', 'draft')"
    )
    op.execute("ALTER TABLE \"Ventas\" ALTER COLUMN estado SET DEFAULT 'completada'")
    op.create_check_constraint("ck_ventas_estado", "Ventas", "estado IN ('completada', 'anulada')")
    op.drop_constraint(None, "Ventas", type_="foreignkey")
    op.drop_column("Ventas", "reversed_at")
    op.drop_column("Ventas", "reversed_by")
    op.drop_column("Ventas", "reversed_motivo")
    # Restore the legacy Movimientos default before dropping its new CHECK.
    op.drop_constraint("ck_movimientos_estado", "Movimientos_Financieros", type_="check")
    op.execute(
        "UPDATE \"Movimientos_Financieros\" SET estado = 'activo' WHERE estado = 'confirmed'"
    )
    op.execute("ALTER TABLE \"Movimientos_Financieros\" ALTER COLUMN estado SET DEFAULT 'activo'")
    op.drop_constraint(None, "Movimientos_Financieros", type_="foreignkey")
    op.drop_column("Movimientos_Financieros", "reversed_at")
    op.drop_column("Movimientos_Financieros", "reversed_by")
    op.drop_column("Movimientos_Financieros", "reversed_motivo")
    op.drop_constraint("ck_devoluciones_estado", "Devoluciones", type_="check")
    op.drop_constraint(None, "Devoluciones", type_="foreignkey")
    op.drop_index(op.f("ix_Devoluciones_estado"), table_name="Devoluciones")
    op.drop_column("Devoluciones", "reversed_at")
    op.drop_column("Devoluciones", "reversed_by")
    op.drop_column("Devoluciones", "reversed_motivo")
    op.drop_column("Devoluciones", "estado")
    op.drop_index("ix_auditlog_usuario_fecha", table_name="AuditLog")
    op.drop_index("ix_auditlog_request_id", table_name="AuditLog")
    op.drop_index("ix_auditlog_entidad_entity_id", table_name="AuditLog")
    op.drop_index("ix_auditlog_entidad_accion_fecha", table_name="AuditLog")
    op.drop_index(op.f("ix_AuditLog_usuario_id"), table_name="AuditLog")
    op.drop_index(op.f("ix_AuditLog_timestamp"), table_name="AuditLog")
    op.drop_index(op.f("ix_AuditLog_request_id"), table_name="AuditLog")
    op.drop_index(op.f("ix_AuditLog_entity_id"), table_name="AuditLog")
    op.drop_index(op.f("ix_AuditLog_entidad"), table_name="AuditLog")
    op.drop_index(op.f("ix_AuditLog_accion"), table_name="AuditLog")
    op.drop_table("AuditLog")
    # ### end Alembic commands ###
